name: google_play_instant
description: "Flutter plugin for Google play instant API"
version: 0.0.1
homepage: https://github.com/Ayush783/google_play_instant

environment:
  sdk: ^3.5.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.google_play_instant
        pluginClass: GooglePlayInstantPlugin
